### ISSUE TITLE
TelemetryDruidPostAggregator: Cannot deserialize input data due to invalid discriminator value. 'type'='expression'

### ISSUE THREAD

**Issue by daagnew** [CiscoDevNet/intersight-python#65] opened 2024-08-15 17:01 UTC
While creating Telemetry API scripts using any TelemetryDruidPostAggregator with type = 'expression' fails with error: intersight.exceptions.ApiValueError: Cannot deserialize input data due to invalid discriminator value. The OpenAPI document has no mapping for discriminator property 'type'='expression' at path: ()

This also fails using code directly from Intersight Help API docs for Telemetry:

```
group_by_request = TelemetryDruidGroupByRequest(
     query_type = "groupBy",
     data_source = TelemetryDruidDataSource(
         type = "table",
         name = "PhysicalEntities"
     ),
     granularity = TelemetryDruidGranularity(
        type = "period",
        origin = None,
        time_zone = "Europe/Vienna",
        duration = None,
        period = "PT12H"
     ),
     intervals = ["2024-02-20T19:47:00.000Z/2024-02-28T19:47:00.000Z"],
     dimensions = [],
     filter = TelemetryDruidAndFilter(
         type = "and",
         fields = [TelemetryDruidSelectorFilter(
             type = "selector",
             dimension = "instrument.name",
             value = "hw.fan"
         )]
     ),
     aggregations = [TelemetryDruidAggregator(
         type = "longSum",
         name = "count",
         field_name = "hw.fan.speed_count"
     ),TelemetryDruidAggregator(
         type = "longSum",
         name = "hw.fan.speed-Sum",
         field_name = "hw.fan.speed"
     )],
     post_aggregations = [TelemetryDruidPostAggregator(
         type = "expression",
         name = "post_aggregation",
         expression = "(\"hw.fan.speed-Sum\" / \"count\")"
    )]
)
api_instance = telemetry_api.TelemetryApi(api_client)
api_response = api_instance.query_telemetry_group_by(group_by_request)
for entry in api_response:
    print(f"{entry['timestamp']} - {entry['event']}")

===========================

Traceback (most recent call last):
  File "/Users/user/metrictest.py", line 84, in <module>
    post_aggregations = [TelemetryDruidPostAggregator(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/intersight/model_utils.py", line 283, in __new__
    raise ApiValueError(
intersight.exceptions.ApiValueError: Cannot deserialize input data due to invalid discriminator value. The OpenAPI document has no mapping for discriminator property 'type'='expression' at path: ()

```

**Comment by the-akhil-nair** [comment] 2024-08-20 12:25
Bug submitter confirmed that with latest python SDK (v1.0.11.17956), the issue is resolved. Hence closing the Issue.

**Closed by the-akhil-nair** 2024-08-20 12:25 UTC
